// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIkrQ7iY-kzbyJmXmQrSLniNcFDmpETYE',
    appId: '1:500672258345:web:c1bb817fef90021d575738',
    messagingSenderId: '500672258345',
    projectId: 'fit-sense-ai',
    authDomain: 'fit-sense-ai.firebaseapp.com',
    storageBucket: 'fit-sense-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLTcweGBr7PsxC6BxvzIoFvrB5zrRjm1I',
    appId: '1:500672258345:android:d2b1e2a2001c4d48575738',
    messagingSenderId: '500672258345',
    projectId: 'fit-sense-ai',
    storageBucket: 'fit-sense-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbcYTtG1lSOQgSQ_sWDXvlZf5yaFCHwF8',
    appId: '1:500672258345:ios:36f84e726ec1db14575738',
    messagingSenderId: '500672258345',
    projectId: 'fit-sense-ai',
    storageBucket: 'fit-sense-ai.appspot.com',
    iosBundleId: 'com.example.fitsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbcYTtG1lSOQgSQ_sWDXvlZf5yaFCHwF8',
    appId: '1:500672258345:ios:36f84e726ec1db14575738',
    messagingSenderId: '500672258345',
    projectId: 'fit-sense-ai',
    storageBucket: 'fit-sense-ai.appspot.com',
    iosBundleId: 'com.example.fitsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIkrQ7iY-kzbyJmXmQrSLniNcFDmpETYE',
    appId: '1:500672258345:web:29725256554c57a1575738',
    messagingSenderId: '500672258345',
    projectId: 'fit-sense-ai',
    authDomain: 'fit-sense-ai.firebaseapp.com',
    storageBucket: 'fit-sense-ai.appspot.com',
  );
}
